### ISSUE TITLE
Add endpoint to get only user's projects.

### ISSUE THREAD

**Issue by mariogarcia** [kaleidos-ventures/taiga-importer-api-client#4]
At the moment the list of projects includes all Taiga public projects. I would add a new method apart from listing all projects.

The API endpoint at Taiga API is : "https://api.taiga.io/api/v1/projects?member={userId}"

**Comment by superalex** [comment]
Hello @mariogarcia, this endpoint exists, should we close this issue?

**Comment by mariogarcia** [comment]
Yes you can

**Comment by jespino** [comment]
Thanks! :smiley:
